---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Remount the file system
    mount:
      path: /mount1
      src: /dev/vg04/lv_web1
      fstype: ext4
      opts: rw,noatime,noexec,nodev
      dump: "1"
      passno: "2"
      state: remounted
